### ISSUE TITLE
[FEATURE] Add Environment Variables to portal_config

### ISSUE THREAD

**Issue by msouff** [tethysplatform/tethys#1039]
**Describe the solution you'd like**

portal_config.yml
```yaml
settings:
  ...
  ENVIRONMENT_VARIABLES:
    VAR1: "val1"
    VAR2: "val2"
  ...
```

settings.py
```Python
...
# Add environment variables
ENVIRONMENT_VARIABLES = portal_config_settings.pop("ENVIRONMENT_VARIABLES", {})
for var, val in ENVIRONMENT_VARIABLES.items():
    os.environ[var] = val
...
```

**Additional context**
This would make it easier to add or overwrite portal and app related environment variables and keep track of them in the portal_config.
