### ISSUE TITLE
MFA bug is hiding API Token

### ISSUE THREAD

**Issue by ezrajrice** [tethysplatform/tethys#626]
I’m having an issue where the API token isn’t visible for users when MFA is configured and not required. 
My sample account has Email MFA configured and is working, but cannot see the API Token.
 
My MFA configuration in the portal_config.yml file is:
```YAML
  MFA_CONFIG:
    MFA_REQUIRED: False
    ADMIN_MFA_REQUIRED: False
    SSO_MFA_REQUIRED: False
    MFA_RECHECK: True
    MFA_RECHECK_MIN: 60
    MFA_RECHECK_MAX: 180
    MFA_QUICKLOGIN: True
    TOKEN_ISSUER_NAME: 'SMARTLINE Portal (Dev)'
    MFA_UNALLOWED_METHODS: ['U2F', 'FIDO2', 'Trusted_Devices']
```
I believe the bug to be in the template in tethys_portal/templates/tethys_portal/user/profile.html
```html
              <span class="parameter">Token:</span>
              {% if user.username == context_user.username %}
                {% if mfa_required and has_mfa %}
                <span class="value">{{ user_token }}</span>
                {% else %}
                <span class="value">Enable 2-Step verification to view token</span>
                {% endif %}
              {% else %}
                <span class="label label-info">Private</span>
              {% endif %}
```
This is the change that I think should be made:
`{% if mfa_required and has_mfa %}` -> `{% if not mfa_required or (mfa_required and has_mfa) %}`

The issue seems to only occur when MFA_REQUIRED is False.
