### ISSUE TITLE
[FEATURE] Make settings.py more extensible

### ISSUE THREAD

**Issue by sdc50** [tethysplatform/tethys#968]
Currently the `settings.py` file is abstracted away from the Tethys user and all user manipulated settings are accessed through the `portal_config.yml` file.

This has the advantage of being simpler and easier to access for users, but takes away some of the capability that the `settings.py` file provides, e.g. loading settings from environment variables and using Python logic to specify settings.

I propose that we enhance the settings in some/all of the following ways:

- Add an `ADDITIONAL_SETTINGS_FILES` setting that takes a list of dot-path, importable modules to load into the `settings.py`
- Add a pre-processor to the `portal_config.yml` file to expand environment variables

**Comment by sdc50** [comment]
Thoughts on `ADDITIONAL_SETTINGS_FILES`:

Example usage in `portal_config.yml`:

```yaml
settings:
  ADDITIONAL_SETTINGS_FILES:
  - tethysext.my_extension.settings.py
  - my_package.tethys_addons.settings.py
  - tethys_portal.additional_settings.optional_feature_settings.py
```

Possible implementation in `settings.py`:

```python
def get__all__(mod):
    try:
        return mod.__all__
    except AttributeError:
        return [a for a in dir(mod) if not a.startswith('__')]

ADDITIONAL_SETTINGS_FILES = portal_config_settings.pop("ADDITIONAL_SETTINGS_FILES", [])
for settings_module in ADDITIONAL_SETTINGS_FILES:
    mod = import_module(settings_module)
    all_settings = get__all__(mod)
    for setting in all_settings:
        value = getattr(setting, mod)
        setattr(this_module, setting, value)

```
